# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="minimal"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration
export HISTSIZE=100000
export SAVEHIST=100000

# Aliases
alias ll='ls -alFG'
alias la='ls -A'
alias l='ls -CF'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Neovim / vi
if command -v /snap/bin/nvim >/dev/null 2>&1; then
  alias nvim='/snap/bin/nvim'
  alias vi='nvim'
  alias vimdiff='/snap/bin/nvim -d'
  export VISUAL='/snap/bin/nvim'
elif command -v nvim >/dev/null 2>&1; then
  alias vi='nvim'
  alias vimdiff='nvim -d'
  export VISUAL='nvim'
else
  alias vi='vim'
  export VISUAL='vim'
fi
export EDITOR="$VISUAL"

# Alert alias
if [[ "$OSTYPE" == "darwin"* ]]; then
  alias alert='osascript -e '\''display notification "Command finished" with title "Terminal"'\'''
else
  alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
fi

[[ -f "$HOME/shared/repos/yt-dlp/yt_dlp/__main__.py" ]] && alias yd="python $HOME/shared/repos/yt-dlp/yt_dlp/__main__.py --no-mtime"

if command -v python3.12 >/dev/null 2>&1; then
  alias python="python3.12"
  alias python3="python3.12"
elif command -v python3 >/dev/null 2>&1; then
  alias python="python3"
fi

[[ -x "$HOME/.local/bin/codex" ]] && alias codex="FORCE_COLOR=1 $HOME/.local/bin/codex"
[[ -x "/usr/local/bin/ctags" ]] && alias ctags='/usr/local/bin/ctags'

# Environment variables
export LC_ALL=en_US.UTF-8 
export LANG="$LC_ALL" 
export CPPFLAGS=-U_FORTIFY_SOURCE
[[ -d "$HOME/ffmpeg_build/lib/pkgconfig" ]] && export PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig:$PKG_CONFIG_PATH"
[[ -d "$HOME/repos/go" ]] && export GOPATH="$HOME/repos/go"
export GTAGSLABEL=pygments
export GEMINI_API_KEY="AIzaSyA4qJCFomAqpG16zXA7BE6Uomc03zNzun8"
export SVGA_VGPU10=1

# PATH configuration (cross-platform)
path_dirs=(
  "$HOME/.local/bin"
  "$HOME/.opencode/bin"
  "$HOME/bin/dev_ssh_scripts"
  "$HOME/bin"
  "$HOME/myrepo"
  "/opt/homebrew/bin"
  "/opt/homebrew/sbin"
  "/usr/local/bin"
  "/usr/local/opt/bin"
  "/Library/TeX/texbin"
)
for dir in "${path_dirs[@]}"; do
  if [[ -d "$dir" && ":$PATH:" != *":$dir:"* ]]; then
    export PATH="$dir:$PATH"
  fi
done

# Vi mode & Cursor settings
bindkey -v
export KEYTIMEOUT=1

_set_cursor() {
  printf '\e[%s q' "$1"
}

zle-keymap-select () {
  case $KEYMAP in
    vicmd)      _set_cursor 2 ;; # Steady Block for Normal mode
    viins|main) _set_cursor 1 ;; # Blinking Block for Insert mode
  esac
}
zle -N zle-keymap-select

zle-line-init () {
  zle -K viins
  _set_cursor 1
}
zle -N zle-line-init

zle-line-finish () {
  _set_cursor 2
}
zle -N zle-line-finish

precmd() {
  _set_cursor 1 # Reset to blinking block on each new prompt
}

# Auto-start tmux (if installed and interactive)
if command -v tmux >/dev/null 2>&1 && [ ! "$TMUX" ]; then
    tmux attach -t main 2>/dev/null || tmux new -s main
fi

export LS_COLORS="$LS_COLORS:ow=1;34:tw=1;34:"
#
# Conda (if present on macOS / Linux)
if [ -d "/usr/local/Caskroom/miniconda/base" ]; then
  __conda_setup="$('/usr/local/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
  if [ $? -eq 0 ]; then
    eval "$__conda_setup"
  fi
  unset __conda_setup
fi

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# SDKMAN (must be at the end of the file)
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh" 
